In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [2]:
DATA_DIR = Path("../data/raw")

files = sorted(DATA_DIR.glob("*.csv"))

for f in files:
    print(f.name)

HomeCredit_columns_description.csv
POS_CASH_balance.csv
application_test.csv
application_train.csv
bureau.csv
bureau_balance.csv
credit_card_balance.csv
installments_payments.csv
previous_application.csv
sample_submission.csv

In [3]:
train = pd.read_csv(DATA_DIR / "application_train.csv")
test = pd.read_csv(DATA_DIR / "application_test.csv")

In [4]:
print("Train:", train.shape)
print("Test :", test.shape)

Train: (307511, 122)
Test : (48744, 121)

In [5]:
train["TARGET"].value_counts()

TARGET
0    282686
1     24825
Name: count, dtype: int64

In [6]:
train["TARGET"].value_counts(normalize=True) * 100

TARGET
0    91.927118
1     8.072882
Name: proportion, dtype: float64

In [7]:
target_summary = pd.DataFrame({
    "count": train["TARGET"].value_counts(),
    "percentage": train["TARGET"].value_counts(normalize=True) * 100
})

target_summary

         count  percentage
TARGET
0       282686   91.927118
1        24825    8.072882

In [8]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), str(16)
memory usage: 325.2 MB

In [9]:
train.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
SK_ID_CURR,307511.0,NaN,NaN,NaN,278180.518577,102790.175348,100002.0,189145.5,278202.0,367142.5,456255.0
TARGET,307511.0,NaN,NaN,NaN,0.080729,0.272419,0.0,0.0,0.0,0.0,1.0
NAME_CONTRACT_TYPE,307511,2,Cash loans,278232,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CODE_GENDER,307511,3,F,202448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FLAG_OWN_CAR,307511,2,N,202924,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
AMT_REQ_CREDIT_BUREAU_DAY,265992.0,NaN,NaN,NaN,0.007,0.110757,0.0,0.0,0.0,0.0,9.0
AMT_REQ_CREDIT_BUREAU_WEEK,265992.0,NaN,NaN,NaN,0.034362,0.204685,0.0,0.0,0.0,0.0,8.0
AMT_REQ_CREDIT_BUREAU_MON,265992.0,NaN,NaN,NaN,0.267395,0.916002,0.0,0.0,0.0,0.0,27.0
AMT_REQ_CREDIT_BUREAU_QRT,265992.0,NaN,NaN,NaN,0.265474,0.794056,0.0,0.0,0.0,0.0,261.0
AMT_REQ_CREDIT_BUREAU_YEAR,265992.0,NaN,NaN,NaN,1.899974,1.869295,0.0,0.0,1.0,3.0,25.0

In [10]:
missing = pd.DataFrame({
    "missing_count": train.isna().sum(),
    "missing_pct": train.isna().mean() * 100
})

missing = missing.sort_values("missing_pct", ascending=False)

missing.head(30)

                          missing_count  missing_pct
COMMONAREA_MEDI                  214865    69.872297
COMMONAREA_AVG                   214865    69.872297
COMMONAREA_MODE                  214865    69.872297
NONLIVINGAPARTMENTS_MODE         213514    69.432963
NONLIVINGAPARTMENTS_AVG          213514    69.432963
NONLIVINGAPARTMENTS_MEDI         213514    69.432963
FONDKAPREMONT_MODE               210295    68.386172
LIVINGAPARTMENTS_MODE            210199    68.354953
LIVINGAPARTMENTS_AVG             210199    68.354953
LIVINGAPARTMENTS_MEDI            210199    68.354953
FLOORSMIN_AVG                    208642    67.848630
FLOORSMIN_MODE                   208642    67.848630
FLOORSMIN_MEDI                   208642    67.848630
YEARS_BUILD_MEDI                 204488    66.497784
YEARS_BUILD_MODE                 204488    66.497784
YEARS_BUILD_AVG                  204488    66.497784
OWN_CAR_AGE                      202929    65.990810
LANDAREA_MEDI                    182590    59.376738
LANDAREA_MODE                    182590    59.376738
LANDAREA_AVG                     182590    59.376738
BASEMENTAREA_MEDI                179943    58.515956
BASEMENTAREA_AVG                 179943    58.515956
BASEMENTAREA_MODE                179943    58.515956
EXT_SOURCE_1                     173378    56.381073
NONLIVINGAREA_MODE               169682    55.179164
NONLIVINGAREA_AVG                169682    55.179164
NONLIVINGAREA_MEDI               169682    55.179164
ELEVATORS_MEDI                   163891    53.295980
ELEVATORS_AVG                    163891    53.295980
ELEVATORS_MODE                   163891    53.295980

In [11]:
missing[missing["missing_pct"] > 50]

                          missing_count  missing_pct
COMMONAREA_MEDI                  214865    69.872297
COMMONAREA_AVG                   214865    69.872297
COMMONAREA_MODE                  214865    69.872297
NONLIVINGAPARTMENTS_MODE         213514    69.432963
NONLIVINGAPARTMENTS_AVG          213514    69.432963
NONLIVINGAPARTMENTS_MEDI         213514    69.432963
FONDKAPREMONT_MODE               210295    68.386172
LIVINGAPARTMENTS_MODE            210199    68.354953
LIVINGAPARTMENTS_AVG             210199    68.354953
LIVINGAPARTMENTS_MEDI            210199    68.354953
FLOORSMIN_AVG                    208642    67.848630
FLOORSMIN_MODE                   208642    67.848630
FLOORSMIN_MEDI                   208642    67.848630
YEARS_BUILD_MEDI                 204488    66.497784
YEARS_BUILD_MODE                 204488    66.497784
YEARS_BUILD_AVG                  204488    66.497784
OWN_CAR_AGE                      202929    65.990810
LANDAREA_MEDI                    182590    59.376738
LANDAREA_MODE                    182590    59.376738
LANDAREA_AVG                     182590    59.376738
BASEMENTAREA_MEDI                179943    58.515956
BASEMENTAREA_AVG                 179943    58.515956
BASEMENTAREA_MODE                179943    58.515956
EXT_SOURCE_1                     173378    56.381073
NONLIVINGAREA_MODE               169682    55.179164
NONLIVINGAREA_AVG                169682    55.179164
NONLIVINGAREA_MEDI               169682    55.179164
ELEVATORS_MEDI                   163891    53.295980
ELEVATORS_AVG                    163891    53.295980
ELEVATORS_MODE                   163891    53.295980
WALLSMATERIAL_MODE               156341    50.840783
APARTMENTS_MEDI                  156061    50.749729
APARTMENTS_AVG                   156061    50.749729
APARTMENTS_MODE                  156061    50.749729
ENTRANCES_MEDI                   154828    50.348768
ENTRANCES_AVG                    154828    50.348768
ENTRANCES_MODE                   154828    50.348768
LIVINGAREA_AVG                   154350    50.193326
LIVINGAREA_MODE                  154350    50.193326
LIVINGAREA_MEDI                  154350    50.193326
HOUSETYPE_MODE                   154297    50.176091

In [12]:
numeric_cols = train.select_dtypes(
    include=np.number
).columns.tolist()

categorical_cols = train.select_dtypes(
    exclude=np.number
).columns.tolist()

print("Numeric:", len(numeric_cols))
print("Categorical:", len(categorical_cols))

Numeric: 106
Categorical: 16

In [13]:
print(categorical_cols)

['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'OCCUPATION_TYPE', 'WEEKDAY_APPR_PROCESS_START', 'ORGANIZATION_TYPE', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE']

In [14]:
train.columns.tolist()

['SK_ID_CURR',
 'TARGET',
 'NAME_CONTRACT_TYPE',
 'CODE_GENDER',
 'FLAG_OWN_CAR',
 'FLAG_OWN_REALTY',
 'CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'NAME_TYPE_SUITE',
 'NAME_INCOME_TYPE',
 'NAME_EDUCATION_TYPE',
 'NAME_FAMILY_STATUS',
 'NAME_HOUSING_TYPE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_EMPLOYED',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'OWN_CAR_AGE',
 'FLAG_MOBIL',
 'FLAG_EMP_PHONE',
 'FLAG_WORK_PHONE',
 'FLAG_CONT_MOBILE',
 'FLAG_PHONE',
 'FLAG_EMAIL',
 'OCCUPATION_TYPE',
 'CNT_FAM_MEMBERS',
 'REGION_RATING_CLIENT',
 'REGION_RATING_CLIENT_W_CITY',
 'WEEKDAY_APPR_PROCESS_START',
 'HOUR_APPR_PROCESS_START',
 'REG_REGION_NOT_LIVE_REGION',
 'REG_REGION_NOT_WORK_REGION',
 'LIVE_REGION_NOT_WORK_REGION',
 'REG_CITY_NOT_LIVE_CITY',
 'REG_CITY_NOT_WORK_CITY',
 'LIVE_CITY_NOT_WORK_CITY',
 'ORGANIZATION_TYPE',
 'EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'APARTMENTS_AVG',
 'BASEMENTAREA_AVG',
 'YEARS_BEGINEXPLUATATION_AVG',
 'YEARS_BUILD_AVG',
 'COMMONAREA_AVG',
 'ELEVATORS_AVG',
 'ENTRANCES_AVG',
 'FLOORSMAX_AVG',
 'FLOORSMIN_AVG',
 'LANDAREA_AVG',
 'LIVINGAPARTMENTS_AVG',
 'LIVINGAREA_AVG',
 'NONLIVINGAPARTMENTS_AVG',
 'NONLIVINGAREA_AVG',
 'APARTMENTS_MODE',
 'BASEMENTAREA_MODE',
 'YEARS_BEGINEXPLUATATION_MODE',
 'YEARS_BUILD_MODE',
 'COMMONAREA_MODE',
 'ELEVATORS_MODE',
 'ENTRANCES_MODE',
 'FLOORSMAX_MODE',
 'FLOORSMIN_MODE',
 'LANDAREA_MODE',
 'LIVINGAPARTMENTS_MODE',
 'LIVINGAREA_MODE',
 'NONLIVINGAPARTMENTS_MODE',
 'NONLIVINGAREA_MODE',
 'APARTMENTS_MEDI',
 'BASEMENTAREA_MEDI',
 'YEARS_BEGINEXPLUATATION_MEDI',
 'YEARS_BUILD_MEDI',
 'COMMONAREA_MEDI',
 'ELEVATORS_MEDI',
 'ENTRANCES_MEDI',
 'FLOORSMAX_MEDI',
 'FLOORSMIN_MEDI',
 'LANDAREA_MEDI',
 'LIVINGAPARTMENTS_MEDI',
 'LIVINGAREA_MEDI',
 'NONLIVINGAPARTMENTS_MEDI',
 'NONLIVINGAREA_MEDI',
 'FONDKAPREMONT_MODE',
 'HOUSETYPE_MODE',
 'TOTALAREA_MODE',
 'WALLSMATERIAL_MODE',
 'EMERGENCYSTATE_MODE',
 'OBS_30_CNT_SOCIAL_CIRCLE',
 'DEF_30_CNT_SOCIAL_CIRCLE',
 'OBS_60_CNT_SOCIAL_CIRCLE',
 'DEF_60_CNT_SOCIAL_CIRCLE',
 'DAYS_LAST_PHONE_CHANGE',
 'FLAG_DOCUMENT_2',
 'FLAG_DOCUMENT_3',
 'FLAG_DOCUMENT_4',
 'FLAG_DOCUMENT_5',
 'FLAG_DOCUMENT_6',
 'FLAG_DOCUMENT_7',
 'FLAG_DOCUMENT_8',
 'FLAG_DOCUMENT_9',
 'FLAG_DOCUMENT_10',
 'FLAG_DOCUMENT_11',
 'FLAG_DOCUMENT_12',
 'FLAG_DOCUMENT_13',
 'FLAG_DOCUMENT_14',
 'FLAG_DOCUMENT_15',
 'FLAG_DOCUMENT_16',
 'FLAG_DOCUMENT_17',
 'FLAG_DOCUMENT_18',
 'FLAG_DOCUMENT_19',
 'FLAG_DOCUMENT_20',
 'FLAG_DOCUMENT_21',
 'AMT_REQ_CREDIT_BUREAU_HOUR',
 'AMT_REQ_CREDIT_BUREAU_DAY',
 'AMT_REQ_CREDIT_BUREAU_WEEK',
 'AMT_REQ_CREDIT_BUREAU_MON',
 'AMT_REQ_CREDIT_BUREAU_QRT',
 'AMT_REQ_CREDIT_BUREAU_YEAR']

In [15]:
key_columns = [
    "SK_ID_CURR",
    "TARGET",
    "AMT_INCOME_TOTAL",
    "AMT_CREDIT",
    "AMT_ANNUITY",
    "AMT_GOODS_PRICE",
    "DAYS_BIRTH",
    "DAYS_EMPLOYED",
    "EXT_SOURCE_1",
    "EXT_SOURCE_2",
    "EXT_SOURCE_3"
]

train[key_columns].head()

,SK_ID_CURR,TARGET,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,DAYS_BIRTH,DAYS_EMPLOYED,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3
0,100002,1,202500.0,406597.5,24700.5,351000.0,-9461,-637,0.083037,0.262949,0.139376
1,100003,0,270000.0,1293502.5,35698.5,1129500.0,-16765,-1188,0.311267,0.622246,NaN
2,100004,0,67500.0,135000.0,6750.0,135000.0,-19046,-225,NaN,0.555912,0.729567
3,100006,0,135000.0,312682.5,29686.5,297000.0,-19005,-3039,NaN,0.650442,NaN
4,100007,0,121500.0,513000.0,21865.5,513000.0,-19932,-3038,NaN,0.322738,NaN

In [18]:
train["AGE_YEARS"] = (
    -train["DAYS_BIRTH"] / 365.25
)

In [19]:
train["AGE_YEARS"].describe()

count    307511.000000
mean         43.906900
std          11.947950
min          20.503765
25%          33.984942
50%          43.121150
75%          53.886379
max          69.073238
Name: AGE_YEARS, dtype: float64

In [20]:
train["DAYS_EMPLOYED"].describe()

count    307511.000000
mean      63815.045904
std      141275.766519
min      -17912.000000
25%       -2760.000000
50%       -1213.000000
75%        -289.000000
max      365243.000000
Name: DAYS_EMPLOYED, dtype: float64

In [21]:
tables = [
    "bureau.csv",
    "bureau_balance.csv",
    "previous_application.csv",
    "POS_CASH_balance.csv",
    "installments_payments.csv",
    "credit_card_balance.csv"
]

for table in tables:
    df_sample = pd.read_csv(
        DATA_DIR / table,
        nrows=5
    )

    print("\n", "=" * 60)
    print(table)
    print("Columns:", len(df_sample.columns))
    print(df_sample.columns.tolist())

 ============================================================
bureau.csv
Columns: 17
['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY']

 ============================================================
bureau_balance.csv
Columns: 3
['SK_ID_BUREAU', 'MONTHS_BALANCE', 'STATUS']

 ============================================================
previous_application.csv
Columns: 37
['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY', 'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY', 'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY', 'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE', 'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE', 'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE', 'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE', 'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY', 'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION', 'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION', 'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL']

 ============================================================
POS_CASH_balance.csv
Columns: 8
['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'CNT_INSTALMENT', 'CNT_INSTALMENT_FUTURE', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF']

 ============================================================
installments_payments.csv
Columns: 8
['SK_ID_PREV', 'SK_ID_CURR', 'NUM_INSTALMENT_VERSION', 'NUM_INSTALMENT_NUMBER', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT', 'AMT_INSTALMENT', 'AMT_PAYMENT']

 ============================================================
credit_card_balance.csv
Columns: 23
['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY', 'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF']

In [22]:
def count_rows(filepath):
    with open(filepath, "rb") as f:
        return sum(1 for _ in f) - 1

for table in tables:
    path = DATA_DIR / table
    print(table, count_rows(path))

bureau.csv 1716428
bureau_balance.csv 27299925
previous_application.csv 1670214
POS_CASH_balance.csv 10001358
installments_payments.csv 13605401
credit_card_balance.csv 3840312

In [23]:
data_summary = pd.DataFrame({
    "table": [
        "application_train",
        "application_test",
        "bureau",
        "bureau_balance",
        "previous_application",
        "POS_CASH_balance",
        "installments_payments",
        "credit_card_balance"
    ]
})

data_summary

                   table
0      application_train
1       application_test
2                 bureau
3         bureau_balance
4   previous_application
5       POS_CASH_balance
6  installments_payments
7    credit_card_balance

In [24]:
# ============================================
# DAY 1 — RELATIONSHIP / DATA ARCHITECTURE
# ============================================

# 1. Check applicant IDs
print("TRAIN applicants:", train["SK_ID_CURR"].nunique())
print("TEST applicants :", test["SK_ID_CURR"].nunique())

# 2. Check overlap between train and test
train_ids = set(train["SK_ID_CURR"])
test_ids = set(test["SK_ID_CURR"])

print("Train/Test ID overlap:", len(train_ids & test_ids))

# 3. Check historical tables' applicant coverage
for table in [
    "bureau.csv",
    "previous_application.csv",
    "POS_CASH_balance.csv",
    "installments_payments.csv",
    "credit_card_balance.csv"
]:
    df_sample = pd.read_csv(DATA_DIR / table, nrows=100000)

    coverage = df_sample["SK_ID_CURR"].nunique()

    print(f"{table:30s} unique applicants in sample: {coverage:,}")

# 4. Check bureau -> bureau_balance relationship
bureau_sample = pd.read_csv(
    DATA_DIR / "bureau.csv",
    nrows=100000
)

bureau_balance_sample = pd.read_csv(
    DATA_DIR / "bureau_balance.csv",
    nrows=100000
)

print("\nBureau IDs in sample:",
      bureau_sample["SK_ID_BUREAU"].nunique())

print("Bureau balance IDs in sample:",
      bureau_balance_sample["SK_ID_BUREAU"].nunique())

print(
    "Bureau IDs appearing in bureau_balance sample:",
    len(
        set(bureau_sample["SK_ID_BUREAU"])
        &
        set(bureau_balance_sample["SK_ID_BUREAU"])
    )
)

# 5. Check previous application -> installment/POS/credit card linkage
previous_sample = pd.read_csv(
    DATA_DIR / "previous_application.csv",
    nrows=100000
)

print("\nPrevious application IDs:",
      previous_sample["SK_ID_PREV"].nunique())

for table in [
    "POS_CASH_balance.csv",
    "installments_payments.csv",
    "credit_card_balance.csv"
]:
    df_sample = pd.read_csv(DATA_DIR / table, nrows=100000)

    overlap = len(
        set(previous_sample["SK_ID_PREV"])
        &
        set(df_sample["SK_ID_PREV"])
    )

    print(
        f"{table:30s} SK_ID_PREV overlap: {overlap:,}"
    )

TRAIN applicants: 307511
TEST applicants : 48744
Train/Test ID overlap: 0
bureau.csv                     unique applicants in sample: 23,121
previous_application.csv       unique applicants in sample: 79,977
POS_CASH_balance.csv           unique applicants in sample: 77,469
installments_payments.csv      unique applicants in sample: 48,591
credit_card_balance.csv        unique applicants in sample: 53,383

Bureau IDs in sample: 100000
Bureau balance IDs in sample: 3111
Bureau IDs appearing in bureau_balance sample: 2650

Previous application IDs: 100000
POS_CASH_balance.csv           SK_ID_PREV overlap: 5,339
installments_payments.csv      SK_ID_PREV overlap: 4,042
credit_card_balance.csv        SK_ID_PREV overlap: 2,478